"use client";
import Link from "next/link";
import {useParams,useSearchParams} from "next/navigation";
import {useEffect,useState} from "react";
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
type Accident={accident_date:string|null;diagnosis_date:string|null;onset_date:string|null;location:string|null;description:string|null};
type Claim={claim_id:string;contract_id:string;insured_id:string;claim_number:string;title:string;claim_type:string;status:string;accident:Accident};
const stages=["Case 생성","문서 필요","문서 분석","사용자 확인","보험금 분석","완료"];
export default function ClaimDetail(){const {claimId}=useParams<{claimId:string}>();const search=useSearchParams();const [claim,setClaim]=useState<Claim|null>(null),[error,setError]=useState("");useEffect(()=>{fetch(`${api}/api/claims/${claimId}`,{credentials:"include"}).then(async response=>{if(response.ok)setClaim(await response.json());else setError("Case를 조회할 수 없습니다.")})},[claimId]);async function cancel(){if(!confirm("보험금 분석을 취소하시겠습니까? 기존 Case 데이터는 보관됩니다."))return;const response=await fetch(`${api}/api/claims/${claimId}/cancel`,{method:"POST",credentials:"include"});if(response.ok)setClaim(await response.json());else setError("현재 상태에서는 취소할 수 없습니다.")}if(error)return <main><p role="alert">{error}</p></main>;if(!claim)return <main><p>불러오는 중…</p></main>;return <main>{search.get("created")&&<p className="notice">보험금 분석 Case가 생성되었습니다. 다음 단계로 문서를 등록해야 합니다.</p>}<section className="card"><div className="actions spread"><div><small>{claim.claim_number}</small><h1>{claim.title}</h1></div><span className={`status ${claim.status.toLowerCase()}`}>{claim.status}</span></div><dl><dt>유형</dt><dd>{claim.claim_type}</dd><dt>보험계약</dt><dd><Link href={`/contracts/${claim.contract_id}`}>{claim.contract_id}</Link></dd><dt>피보험자 ID</dt><dd>{claim.insured_id}</dd><dt>사고일</dt><dd>{claim.accident.accident_date??"-"}</dd><dt>진단일</dt><dd>{claim.accident.diagnosis_date??"-"}</dd><dt>발병일</dt><dd>{claim.accident.onset_date??"-"}</dd><dt>사고장소</dt><dd>{claim.accident.location??"-"}</dd><dt>설명</dt><dd>{claim.accident.description??"-"}</dd></dl><h2>진행 Timeline</h2><ol className="timeline">{stages.map((stage,index)=><li className={index<2?"active":""} key={stage}>{stage}</li>)}</ol><div className="actions"><Link className="button" href={`/claims/${claimId}/documents`}>문서 등록 및 관리</Link>{!["CANCELLED","COMPLETED","CLOSED","FAILED"].includes(claim.status)&&<button className="button danger" onClick={()=>void cancel()}>분석 취소</button>}</div></section></main>}
