"use client";

import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Check = { check_code:string; status:string; reviewer_id?:string; reason?:string; reviewed_at?:string };
type Evidence = { id:number; document_type:string; file_name:string; page:number; article_no?:string; article_title?:string; source_text:string; source_url?:string };
type Context = { coverage:Record<string,unknown>; rule:Record<string,unknown>; evidence:Evidence[]; verification:{ checks:Check[]; eligible_for_promotion:boolean; rule_status:string } };
const labels:Record<string,string>={PRODUCT_CODE_MAPPING:"상품 코드 매핑",POLICY_COVERAGE:"약관 담보 일치",PAYMENT_RULE:"지급 조건·산식",EXCLUSIONS_LIMITS:"면책·한도",DISEASE_DEFINITION:"질병 정의",KCD_APPENDIX:"KCD 분류표",SOURCE_REFERENCES:"출처·페이지 근거"};

export default function PolicyVerificationDetail() {
  const {coverageId}=useParams<{coverageId:string}>(); const [data,setData]=useState<Context|null>(null); const [reasons,setReasons]=useState<Record<string,string>>({}); const [promotionReason,setPromotionReason]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch(`${api}/api/admin/policy-db/coverages/${coverageId}/verification-context`,{credentials:"include"});if(!response.ok){setMessage("검증 자료를 조회할 권한이 없거나 담보가 존재하지 않습니다.");return;}setData(await response.json());},[coverageId]);
  useEffect(()=>{fetch(`${api}/api/admin/policy-db/coverages/${coverageId}/verification-context`,{credentials:"include"}).then(async response=>{if(!response.ok){setMessage("검증 자료를 조회할 권한이 없거나 담보가 존재하지 않습니다.");return;}setData(await response.json());}).catch(()=>setMessage("API 서버에 연결할 수 없습니다."));},[coverageId]);
  async function review(code:string,status:"APPROVED"|"REJECTED"){const reason=(reasons[code]??"").trim();if(reason.length<3){setMessage("승인 또는 거절 사유를 3자 이상 입력하세요.");return;}setBusy(true);const response=await fetch(`${api}/api/admin/policy-db/coverages/${coverageId}/verification/${code}`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,reason})});setBusy(false);setMessage(response.ok?`${labels[code]} 검토 결과를 저장했습니다.`:"승인 권한이 없거나 검토 결과 저장에 실패했습니다.");if(response.ok)await load();}
  async function promote(){if(promotionReason.trim().length<3){setMessage("승격 사유를 3자 이상 입력하세요.");return;}if(!confirm("모든 검증 결과와 근거를 확인했습니까? VERIFIED_POLICY 승격은 계산 가능 여부에 영향을 줍니다."))return;setBusy(true);const response=await fetch(`${api}/api/admin/policy-db/coverages/${coverageId}/promote`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:promotionReason})});setBusy(false);setMessage(response.ok?"VERIFIED_POLICY로 승격했습니다.":"승격 조건을 충족하지 못했거나 승인 권한이 없습니다.");if(response.ok)await load();}
  if(!data)return <main><h1>약관 검증</h1><p className={message?"error":""}>{message||"불러오는 중…"}</p></main>;
  return <main><h1>{String(data.coverage.coverage_name)}</h1><p><span className="badge">{data.verification.rule_status}</span> {String(data.coverage.product_code)} · {String(data.coverage.version_name)}</p>{message&&<p className="card">{message}</p>}<section className="card"><h2>검증 체크리스트</h2>{data.verification.checks.map(check=><div className="review-check" key={check.check_code}><div><strong>{labels[check.check_code]??check.check_code}</strong><br/><span className={`badge ${check.status.toLowerCase()}`}>{check.status}</span>{check.reason&&<p className="muted">{check.reason}</p>}</div><textarea aria-label={`${labels[check.check_code]} 검토 사유`} value={reasons[check.check_code]??""} onChange={event=>setReasons({...reasons,[check.check_code]:event.target.value})} placeholder="약관 페이지와 Rule을 대조한 구체적인 사유"/><div className="review-actions"><button disabled={busy} onClick={()=>void review(check.check_code,"APPROVED")}>승인</button><button className="reject" disabled={busy} onClick={()=>void review(check.check_code,"REJECTED")}>거절</button></div></div>)}</section><section className="card"><h2>공식 약관 근거</h2>{data.evidence.map(item=><article key={item.id}><h3>{item.document_type} · p.{item.page} {item.article_no??""}</h3><p className="muted">{item.file_name}</p><div className="evidence">{item.source_text}</div>{item.source_url&&<p><a href={item.source_url} target="_blank" rel="noreferrer">공식 출처 열기</a></p>}</article>)}</section><section className="card"><h2>추출 Rule Snapshot</h2><pre className="evidence">{JSON.stringify(data.rule,null,2)}</pre></section><section className="card"><h2>정책 승격</h2><p>7개 항목이 모두 승인된 경우에만 활성화됩니다.</p><textarea value={promotionReason} onChange={event=>setPromotionReason(event.target.value)} placeholder="승격 사유"/><p><button disabled={busy||!data.verification.eligible_for_promotion} onClick={()=>void promote()}>VERIFIED_POLICY 승격</button></p></section></main>;
}
