"""add insurance contracts

Revision ID: 3f8261322bcf
Revises: c0f8c223575a
Create Date: 2026-08-18 16:10:04.568331
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3f8261322bcf"
down_revision: str | None = "c0f8c223575a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for value in (
            "INSURED_CREATE",
            "INSURED_MODIFY",
            "CONTRACT_CREATE",
            "CONTRACT_MODIFY",
            "CONTRACT_COVERAGE_CREATE",
            "CONTRACT_COVERAGE_MODIFY",
            "CONTRACT_COVERAGE_DEACTIVATE",
        ):
            op.execute(f"ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS '{value}'")
    op.create_table(
        "insureds",
        sa.Column("insured_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", "UNKNOWN", name="gender"), nullable=False),
        sa.Column("identity_token", sa.String(length=255), nullable=True),
        sa.Column(
            "relationship_type",
            sa.Enum("SELF", "SPOUSE", "CHILD", "PARENT", "OTHER", name="relationshiptype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.user_id"], name=op.f("fk_insureds_owner_user_id_users")
        ),
        sa.PrimaryKeyConstraint("insured_id", name=op.f("pk_insureds")),
    )
    op.create_index(op.f("ix_insureds_owner_user_id"), "insureds", ["owner_user_id"], unique=False)
    op.create_table(
        "insurance_contracts",
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("insured_id", sa.Uuid(), nullable=False),
        sa.Column("product_version_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=True),
        sa.Column("policy_number", sa.String(length=150), nullable=True),
        sa.Column("contract_date", sa.Date(), nullable=True),
        sa.Column("coverage_start_date", sa.Date(), nullable=True),
        sa.Column("coverage_end_date", sa.Date(), nullable=True),
        sa.Column(
            "contract_status",
            sa.Enum(
                "ACTIVE", "EXPIRED", "CANCELLED", "SUSPENDED", "UNKNOWN", name="contractstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "registration_method",
            sa.Enum("MANUAL", "OCR", "ADMIN", "API", name="registrationmethod"),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "coverage_end_date IS NULL OR coverage_start_date IS NULL OR "
            "coverage_start_date < coverage_end_date",
            name=op.f("ck_insurance_contracts_contract_coverage_period"),
        ),
        sa.CheckConstraint(
            "coverage_start_date IS NULL OR contract_date IS NULL OR "
            "contract_date <= coverage_start_date",
            name=op.f("ck_insurance_contracts_contract_start_after_contract"),
        ),
        sa.ForeignKeyConstraint(
            ["insured_id"],
            ["insureds.insured_id"],
            name=op.f("fk_insurance_contracts_insured_id_insureds"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.policy_version_id"],
            name=op.f("fk_insurance_contracts_policy_version_id_policy_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["product_version_id"],
            ["product_versions.product_version_id"],
            name=op.f("fk_insurance_contracts_product_version_id_product_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_insurance_contracts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("contract_id", name=op.f("pk_insurance_contracts")),
    )
    op.create_index(
        op.f("ix_insurance_contracts_contract_status"),
        "insurance_contracts",
        ["contract_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_contracts_insured_id"),
        "insurance_contracts",
        ["insured_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_contracts_policy_version_id"),
        "insurance_contracts",
        ["policy_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_contracts_product_version_id"),
        "insurance_contracts",
        ["product_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_contracts_user_id"), "insurance_contracts", ["user_id"], unique=False
    )
    op.create_table(
        "contract_coverages",
        sa.Column("contract_coverage_id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("coverage_id", sa.Uuid(), nullable=False),
        sa.Column("coverage_name_snapshot", sa.String(length=250), nullable=False),
        sa.Column("insured_amount", sa.BigInteger(), nullable=False),
        sa.Column("coverage_start_date", sa.Date(), nullable=True),
        sa.Column("coverage_end_date", sa.Date(), nullable=True),
        sa.Column("payment_limit", sa.BigInteger(), nullable=True),
        sa.Column("payment_count_limit", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "EXPIRED", "CANCELLED", name="coveragestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "coverage_end_date IS NULL OR coverage_start_date IS NULL OR "
            "coverage_start_date < coverage_end_date",
            name=op.f("ck_contract_coverages_contract_coverage_item_period"),
        ),
        sa.CheckConstraint(
            "insured_amount >= 0", name=op.f("ck_contract_coverages_nonnegative_insured_amount")
        ),
        sa.CheckConstraint(
            "payment_count_limit IS NULL OR payment_count_limit >= 0",
            name=op.f("ck_contract_coverages_nonnegative_payment_count"),
        ),
        sa.CheckConstraint(
            "payment_limit IS NULL OR payment_limit >= 0",
            name=op.f("ck_contract_coverages_nonnegative_payment_limit"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["insurance_contracts.contract_id"],
            name=op.f("fk_contract_coverages_contract_id_insurance_contracts"),
        ),
        sa.ForeignKeyConstraint(
            ["coverage_id"],
            ["coverages.coverage_id"],
            name=op.f("fk_contract_coverages_coverage_id_coverages"),
        ),
        sa.PrimaryKeyConstraint("contract_coverage_id", name=op.f("pk_contract_coverages")),
    )
    op.create_index(
        op.f("ix_contract_coverages_contract_id"),
        "contract_coverages",
        ["contract_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_coverages_coverage_id"),
        "contract_coverages",
        ["coverage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_coverages_status"), "contract_coverages", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contract_coverages_status"), table_name="contract_coverages")
    op.drop_index(op.f("ix_contract_coverages_coverage_id"), table_name="contract_coverages")
    op.drop_index(op.f("ix_contract_coverages_contract_id"), table_name="contract_coverages")
    op.drop_table("contract_coverages")
    op.drop_index(op.f("ix_insurance_contracts_user_id"), table_name="insurance_contracts")
    op.drop_index(
        op.f("ix_insurance_contracts_product_version_id"), table_name="insurance_contracts"
    )
    op.drop_index(
        op.f("ix_insurance_contracts_policy_version_id"), table_name="insurance_contracts"
    )
    op.drop_index(op.f("ix_insurance_contracts_insured_id"), table_name="insurance_contracts")
    op.drop_index(op.f("ix_insurance_contracts_contract_status"), table_name="insurance_contracts")
    op.drop_table("insurance_contracts")
    op.drop_index(op.f("ix_insureds_owner_user_id"), table_name="insureds")
    op.drop_table("insureds")
    # ### end Alembic commands ###
