"""add insurance master

Revision ID: c0f8c223575a
Revises: 0001_foundation
Create Date: 2026-08-18 15:53:49.876770
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c0f8c223575a"
down_revision: str | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for value in (
            "INSURANCE_COMPANY_CREATE",
            "INSURANCE_COMPANY_MODIFY",
            "INSURANCE_PRODUCT_CREATE",
            "INSURANCE_PRODUCT_MODIFY",
            "PRODUCT_VERSION_CREATE",
            "POLICY_CREATE",
            "POLICY_MODIFY",
            "POLICY_VERSION_CREATE",
            "POLICY_VERSION_MODIFY",
            "POLICY_CLAUSE_CREATE",
            "POLICY_CLAUSE_MODIFY",
            "COVERAGE_CREATE",
            "COVERAGE_MODIFY",
            "RULE_CREATE",
            "RULE_MODIFY",
        ):
            op.execute(f"ALTER TYPE auditeventtype ADD VALUE IF NOT EXISTS '{value}'")
    op.create_table(
        "coverages",
        sa.Column("coverage_id", sa.Uuid(), nullable=False),
        sa.Column("standard_code", sa.String(length=80), nullable=False),
        sa.Column("coverage_name", sa.String(length=250), nullable=False),
        sa.Column("coverage_category", sa.String(length=100), nullable=False),
        sa.Column(
            "insurance_type",
            sa.Enum(
                "THIRD_PARTY",
                "LIFE",
                "INDEMNITY",
                "AUTO",
                "LIABILITY",
                "WORKERS_COMP",
                name="insurancetype",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="masterstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("coverage_id", name=op.f("pk_coverages")),
    )
    op.create_index(
        op.f("ix_coverages_coverage_category"), "coverages", ["coverage_category"], unique=False
    )
    op.create_index(
        op.f("ix_coverages_insurance_type"), "coverages", ["insurance_type"], unique=False
    )
    op.create_index(op.f("ix_coverages_standard_code"), "coverages", ["standard_code"], unique=True)
    op.create_index(op.f("ix_coverages_status"), "coverages", ["status"], unique=False)
    op.create_table(
        "insurance_companies",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("company_code", sa.String(length=50), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("company_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="masterstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("company_id", name=op.f("pk_insurance_companies")),
    )
    op.create_index(
        op.f("ix_insurance_companies_company_code"),
        "insurance_companies",
        ["company_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_insurance_companies_status"), "insurance_companies", ["status"], unique=False
    )
    op.create_table(
        "coverage_aliases",
        sa.Column("alias_id", sa.Uuid(), nullable=False),
        sa.Column("coverage_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("alias_name", sa.String(length=250), nullable=False),
        sa.Column("normalized_name", sa.String(length=250), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["insurance_companies.company_id"],
            name=op.f("fk_coverage_aliases_company_id_insurance_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["coverage_id"],
            ["coverages.coverage_id"],
            name=op.f("fk_coverage_aliases_coverage_id_coverages"),
        ),
        sa.PrimaryKeyConstraint("alias_id", name=op.f("pk_coverage_aliases")),
        sa.UniqueConstraint(
            "coverage_id", "company_id", "normalized_name", name="uq_coverage_alias"
        ),
    )
    op.create_index(
        op.f("ix_coverage_aliases_company_id"), "coverage_aliases", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_coverage_aliases_coverage_id"), "coverage_aliases", ["coverage_id"], unique=False
    )
    op.create_index(
        op.f("ix_coverage_aliases_normalized_name"),
        "coverage_aliases",
        ["normalized_name"],
        unique=False,
    )
    op.create_table(
        "insurance_products",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("product_code", sa.String(length=80), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column(
            "insurance_type",
            sa.Enum(
                "THIRD_PARTY",
                "LIFE",
                "INDEMNITY",
                "AUTO",
                "LIABILITY",
                "WORKERS_COMP",
                name="insurancetype",
            ),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="masterstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["insurance_companies.company_id"],
            name=op.f("fk_insurance_products_company_id_insurance_companies"),
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_insurance_products")),
        sa.UniqueConstraint("company_id", "product_code", name="uq_product_company_code"),
    )
    op.create_index(
        op.f("ix_insurance_products_company_id"), "insurance_products", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_products_insurance_type"),
        "insurance_products",
        ["insurance_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_products_product_code"),
        "insurance_products",
        ["product_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_products_status"), "insurance_products", ["status"], unique=False
    )
    op.create_table(
        "product_versions",
        sa.Column("product_version_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("version_name", sa.String(length=80), nullable=False),
        sa.Column("sale_start_date", sa.Date(), nullable=True),
        sa.Column("sale_end_date", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "status", sa.Enum("DRAFT", "ACTIVE", "DEPRECATED", name="versionstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_from <= effective_to",
            name=op.f("ck_product_versions_product_effective_period"),
        ),
        sa.CheckConstraint(
            "sale_end_date IS NULL OR sale_start_date IS NULL OR sale_start_date <= sale_end_date",
            name=op.f("ck_product_versions_product_sale_period"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["insurance_products.product_id"],
            name=op.f("fk_product_versions_product_id_insurance_products"),
        ),
        sa.PrimaryKeyConstraint("product_version_id", name=op.f("pk_product_versions")),
        sa.UniqueConstraint("product_id", "version_name", name="uq_product_version_name"),
    )
    op.create_index(
        op.f("ix_product_versions_product_id"), "product_versions", ["product_id"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("product_version_id", sa.Uuid(), nullable=False),
        sa.Column("policy_name", sa.String(length=250), nullable=False),
        sa.Column(
            "policy_type", sa.Enum("GENERAL", "SPECIAL", "RIDER", name="policytype"), nullable=False
        ),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="masterstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_version_id"],
            ["product_versions.product_version_id"],
            name=op.f("fk_policies_product_version_id_product_versions"),
        ),
        sa.PrimaryKeyConstraint("policy_id", name=op.f("pk_policies")),
    )
    op.create_index(
        op.f("ix_policies_product_version_id"), "policies", ["product_version_id"], unique=False
    )
    op.create_table(
        "policy_versions",
        sa.Column("policy_version_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("version_code", sa.String(length=80), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("published_date", sa.Date(), nullable=True),
        sa.Column("previous_version_id", sa.Uuid(), nullable=True),
        sa.Column("file_hash", sa.String(length=128), nullable=True),
        sa.Column("source_file_uri", sa.String(length=1000), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PROCESSING",
                "REVIEW_REQUIRED",
                "APPROVED",
                "ACTIVE",
                "DEPRECATED",
                name="policyversionstatus",
            ),
            nullable=False,
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from <= effective_to",
            name=op.f("ck_policy_versions_policy_effective_period"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.user_id"], name=op.f("fk_policy_versions_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.policy_id"],
            name=op.f("fk_policy_versions_policy_id_policies"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["policy_versions.policy_version_id"],
            name=op.f("fk_policy_versions_previous_version_id_policy_versions"),
        ),
        sa.PrimaryKeyConstraint("policy_version_id", name=op.f("pk_policy_versions")),
        sa.UniqueConstraint("policy_id", "version_code", name="uq_policy_version_code"),
    )
    op.create_index(
        op.f("ix_policy_versions_effective_from"),
        "policy_versions",
        ["effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_versions_effective_to"), "policy_versions", ["effective_to"], unique=False
    )
    op.create_index(
        op.f("ix_policy_versions_policy_id"), "policy_versions", ["policy_id"], unique=False
    )
    op.create_index(op.f("ix_policy_versions_status"), "policy_versions", ["status"], unique=False)
    op.create_table(
        "benefit_rules",
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("coverage_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sa.String(length=250), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum(
                "ELIGIBILITY", "EXCLUSION", "REDUCTION", "CALCULATION", "LIMIT", name="ruletype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "AI_EXTRACTED",
                "REVIEW_REQUIRED",
                "TESTING",
                "APPROVED",
                "ACTIVE",
                "DEPRECATED",
                name="rulestatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["coverage_id"],
            ["coverages.coverage_id"],
            name=op.f("fk_benefit_rules_coverage_id_coverages"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.policy_version_id"],
            name=op.f("fk_benefit_rules_policy_version_id_policy_versions"),
        ),
        sa.PrimaryKeyConstraint("rule_id", name=op.f("pk_benefit_rules")),
    )
    op.create_index(
        op.f("ix_benefit_rules_coverage_id"), "benefit_rules", ["coverage_id"], unique=False
    )
    op.create_index(
        op.f("ix_benefit_rules_policy_version_id"),
        "benefit_rules",
        ["policy_version_id"],
        unique=False,
    )
    op.create_index(op.f("ix_benefit_rules_status"), "benefit_rules", ["status"], unique=False)
    op.create_table(
        "policy_clauses",
        sa.Column("clause_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=False),
        sa.Column("article_number", sa.String(length=80), nullable=True),
        sa.Column("article_title", sa.String(length=300), nullable=True),
        sa.Column("paragraph_number", sa.String(length=80), nullable=True),
        sa.Column("item_number", sa.String(length=80), nullable=True),
        sa.Column("clause_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("source_bbox", sa.JSON(), nullable=True),
        sa.Column("text_hash", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.policy_version_id"],
            name=op.f("fk_policy_clauses_policy_version_id_policy_versions"),
        ),
        sa.PrimaryKeyConstraint("clause_id", name=op.f("pk_policy_clauses")),
    )
    op.create_index(
        op.f("ix_policy_clauses_policy_version_id"),
        "policy_clauses",
        ["policy_version_id"],
        unique=False,
    )
    op.create_table(
        "benefit_rule_clauses",
        sa.Column("link_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("clause_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["clause_id"],
            ["policy_clauses.clause_id"],
            name=op.f("fk_benefit_rule_clauses_clause_id_policy_clauses"),
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["benefit_rules.rule_id"],
            name=op.f("fk_benefit_rule_clauses_rule_id_benefit_rules"),
        ),
        sa.PrimaryKeyConstraint("link_id", name=op.f("pk_benefit_rule_clauses")),
        sa.UniqueConstraint("rule_id", "clause_id", name="uq_rule_clause"),
    )
    op.create_index(
        op.f("ix_benefit_rule_clauses_clause_id"),
        "benefit_rule_clauses",
        ["clause_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_benefit_rule_clauses_rule_id"), "benefit_rule_clauses", ["rule_id"], unique=False
    )
    op.create_table(
        "rule_versions",
        sa.Column("rule_version_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("rule_definition", sa.JSON(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "AI_EXTRACTED",
                "REVIEW_REQUIRED",
                "TESTING",
                "APPROVED",
                "ACTIVE",
                "DEPRECATED",
                name="rulestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum("MANUAL", "AI_EXTRACTED", "MIGRATED", name="rulesourcetype"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.user_id"], name=op.f("fk_rule_versions_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.user_id"], name=op.f("fk_rule_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["benefit_rules.rule_id"],
            name=op.f("fk_rule_versions_rule_id_benefit_rules"),
        ),
        sa.PrimaryKeyConstraint("rule_version_id", name=op.f("pk_rule_versions")),
        sa.UniqueConstraint("rule_id", "version_no", name="uq_rule_version_no"),
    )
    op.create_index(op.f("ix_rule_versions_rule_id"), "rule_versions", ["rule_id"], unique=False)
    op.create_index(op.f("ix_rule_versions_status"), "rule_versions", ["status"], unique=False)
    op.create_table(
        "rule_conditions",
        sa.Column("condition_id", sa.Uuid(), nullable=False),
        sa.Column("rule_version_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("fact_path", sa.String(length=250), nullable=False),
        sa.Column(
            "operator",
            sa.Enum(
                "EQ",
                "NE",
                "GT",
                "GTE",
                "LT",
                "LTE",
                "IN",
                "NOT_IN",
                "BETWEEN",
                "EXISTS",
                "NOT_EXISTS",
                name="ruleoperator",
            ),
            nullable=False,
        ),
        sa.Column("comparison_value", sa.JSON(), nullable=True),
        sa.Column("logical_operator", sa.Enum("AND", "OR", name="logicaloperator"), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.rule_version_id"],
            name=op.f("fk_rule_conditions_rule_version_id_rule_versions"),
        ),
        sa.PrimaryKeyConstraint("condition_id", name=op.f("pk_rule_conditions")),
        sa.UniqueConstraint("rule_version_id", "sequence_no", name="uq_rule_condition_sequence"),
    )
    op.create_index(
        op.f("ix_rule_conditions_rule_version_id"),
        "rule_conditions",
        ["rule_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rule_conditions_rule_version_id"), table_name="rule_conditions")
    op.drop_table("rule_conditions")
    op.drop_index(op.f("ix_rule_versions_status"), table_name="rule_versions")
    op.drop_index(op.f("ix_rule_versions_rule_id"), table_name="rule_versions")
    op.drop_table("rule_versions")
    op.drop_index(op.f("ix_benefit_rule_clauses_rule_id"), table_name="benefit_rule_clauses")
    op.drop_index(op.f("ix_benefit_rule_clauses_clause_id"), table_name="benefit_rule_clauses")
    op.drop_table("benefit_rule_clauses")
    op.drop_index(op.f("ix_policy_clauses_policy_version_id"), table_name="policy_clauses")
    op.drop_table("policy_clauses")
    op.drop_index(op.f("ix_benefit_rules_status"), table_name="benefit_rules")
    op.drop_index(op.f("ix_benefit_rules_policy_version_id"), table_name="benefit_rules")
    op.drop_index(op.f("ix_benefit_rules_coverage_id"), table_name="benefit_rules")
    op.drop_table("benefit_rules")
    op.drop_index(op.f("ix_policy_versions_status"), table_name="policy_versions")
    op.drop_index(op.f("ix_policy_versions_policy_id"), table_name="policy_versions")
    op.drop_index(op.f("ix_policy_versions_effective_to"), table_name="policy_versions")
    op.drop_index(op.f("ix_policy_versions_effective_from"), table_name="policy_versions")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_policies_product_version_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_product_versions_product_id"), table_name="product_versions")
    op.drop_table("product_versions")
    op.drop_index(op.f("ix_insurance_products_status"), table_name="insurance_products")
    op.drop_index(op.f("ix_insurance_products_product_code"), table_name="insurance_products")
    op.drop_index(op.f("ix_insurance_products_insurance_type"), table_name="insurance_products")
    op.drop_index(op.f("ix_insurance_products_company_id"), table_name="insurance_products")
    op.drop_table("insurance_products")
    op.drop_index(op.f("ix_coverage_aliases_normalized_name"), table_name="coverage_aliases")
    op.drop_index(op.f("ix_coverage_aliases_coverage_id"), table_name="coverage_aliases")
    op.drop_index(op.f("ix_coverage_aliases_company_id"), table_name="coverage_aliases")
    op.drop_table("coverage_aliases")
    op.drop_index(op.f("ix_insurance_companies_status"), table_name="insurance_companies")
    op.drop_index(op.f("ix_insurance_companies_company_code"), table_name="insurance_companies")
    op.drop_table("insurance_companies")
    op.drop_index(op.f("ix_coverages_status"), table_name="coverages")
    op.drop_index(op.f("ix_coverages_standard_code"), table_name="coverages")
    op.drop_index(op.f("ix_coverages_insurance_type"), table_name="coverages")
    op.drop_index(op.f("ix_coverages_coverage_category"), table_name="coverages")
    op.drop_table("coverages")
    # ### end Alembic commands ###
