"use client";
/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable react-hooks/exhaustive-deps */
import Link from "next/link";
import {useParams} from "next/navigation";
import {useEffect,useState} from "react";
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
type Calculation={insured_amount_snapshot:number;payment_rate_snapshot:string|null;calculation_formula:string;gross_amount:number;deduction_amount:number;final_amount:number;calculation_status:string;calculation_version:number};
type Evidence={evidence_id:string;evidence_type:string;summary:string;document_id:string|null;page_number:number|null;source_bbox:object|null;source_snapshot:Record<string,unknown>};
type Trace={sequence:number;step_type:string;result:string};
export default function BasisPage(){const {claimId,calculationId}=useParams<{claimId:string;calculationId:string}>();const [calculation,setCalculation]=useState<Calculation|null>(null),[evidence,setEvidence]=useState<Evidence[]>([]),[trace,setTrace]=useState<Trace[]>([]),[message,setMessage]=useState("");async function load(){const [c,e,t]=await Promise.all([fetch(`${api}/api/calculations/${calculationId}`,{credentials:"include"}),fetch(`${api}/api/calculations/${calculationId}/evidence`,{credentials:"include"}),fetch(`${api}/api/calculations/${calculationId}/trace`,{credentials:"include"})]);if(c.ok)setCalculation(await c.json());if(e.ok)setEvidence(await e.json());if(t.ok)setTrace(await t.json())}useEffect(()=>{void load()},[calculationId]);async function build(){const r=await fetch(`${api}/api/calculations/${calculationId}/evidence`,{method:"POST",credentials:"include"});setMessage(r.ok?"근거사슬이 생성되었습니다.":"필수 약관 또는 원본문서 근거를 확인해야 합니다.");await load()}if(!calculation)return <main><p>계산 근거를 불러오는 중…</p></main>;const clauses=evidence.filter(x=>x.evidence_type==="POLICY_CLAUSE"),facts=evidence.filter(x=>x.evidence_type==="VERIFIED_FACT");return <main><div className="actions spread"><h1>담보별 상세결과</h1><Link href={`/claims/${claimId}/result`}>분석결과로 돌아가기</Link></div><section className="card calculation-box"><span className="status">{calculation.calculation_status} · V{calculation.calculation_version}</span><p>가입금액 Snapshot <strong>{calculation.insured_amount_snapshot.toLocaleString("ko-KR")}원</strong></p><p>지급률 <strong>{calculation.payment_rate_snapshot??"해당 없음"}</strong></p><p>계산식 <code>{calculation.calculation_formula}</code></p><p>공제액 {calculation.deduction_amount.toLocaleString("ko-KR")}원</p><strong className="amount">예상 보험금 {calculation.final_amount.toLocaleString("ko-KR")}원</strong></section>{evidence.length===0&&<section className="card"><h2>계산 근거 준비 필요</h2><p>근거가 완성되기 전에는 이 계산을 완전한 결과로 취급하지 않습니다.</p><button className="button" onClick={()=>void build()}>근거사슬 생성</button>{message&&<p>{message}</p>}</section>}<section className="card"><h2>판단 과정</h2><ol>{trace.map(step=><li key={step.sequence}><strong>{step.step_type}</strong> — {step.result}</li>)}</ol></section><section className="card"><h2>적용 약관</h2>{clauses.map(item=><p key={item.evidence_id}>{item.summary} <Link href={`/claims/${claimId}/calculations/${calculationId}/policy`}>원문 약관 보기</Link></p>)}</section><section className="card"><h2>사용한 의료정보</h2>{facts.map(item=><article key={item.evidence_id}><strong>{String(item.source_snapshot.fact_type)}</strong><p>{String(item.source_snapshot.verified_value)} · {String(item.source_snapshot.verification_status)}</p>{item.document_id&&<a href={`${api}/api/documents/${item.document_id}/content?page=${item.page_number??1}`} target="_blank" rel="noreferrer">의료문서 원문 보기 {item.page_number&&`(${item.page_number}쪽)`}</a>}{item.source_bbox&&<small> · 원문 위치정보 있음</small>}</article>)}</section></main>}
