import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import JSON, DateTime, Enum, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from domain.user.models import utc_now
from infrastructure.database.base import Base


class AuditEventType(enum.StrEnum):
    LOGIN = "LOGIN"
    LOGIN_FAIL = "LOGIN_FAIL"
    USER_REGISTER = "USER_REGISTER"
    LOGOUT = "LOGOUT"
    INSURANCE_COMPANY_CREATE = "INSURANCE_COMPANY_CREATE"
    INSURANCE_COMPANY_MODIFY = "INSURANCE_COMPANY_MODIFY"
    INSURANCE_PRODUCT_CREATE = "INSURANCE_PRODUCT_CREATE"
    INSURANCE_PRODUCT_MODIFY = "INSURANCE_PRODUCT_MODIFY"
    PRODUCT_VERSION_CREATE = "PRODUCT_VERSION_CREATE"
    POLICY_CREATE = "POLICY_CREATE"
    POLICY_MODIFY = "POLICY_MODIFY"
    POLICY_VERSION_CREATE = "POLICY_VERSION_CREATE"
    POLICY_VERSION_MODIFY = "POLICY_VERSION_MODIFY"
    POLICY_CLAUSE_CREATE = "POLICY_CLAUSE_CREATE"
    POLICY_CLAUSE_MODIFY = "POLICY_CLAUSE_MODIFY"
    COVERAGE_CREATE = "COVERAGE_CREATE"
    COVERAGE_MODIFY = "COVERAGE_MODIFY"
    RULE_CREATE = "RULE_CREATE"
    RULE_MODIFY = "RULE_MODIFY"
    INSURED_CREATE = "INSURED_CREATE"
    INSURED_MODIFY = "INSURED_MODIFY"
    CONTRACT_CREATE = "CONTRACT_CREATE"
    CONTRACT_MODIFY = "CONTRACT_MODIFY"
    CONTRACT_COVERAGE_CREATE = "CONTRACT_COVERAGE_CREATE"
    CONTRACT_COVERAGE_MODIFY = "CONTRACT_COVERAGE_MODIFY"
    CONTRACT_COVERAGE_DEACTIVATE = "CONTRACT_COVERAGE_DEACTIVATE"
    CLAIM_CREATE = "CLAIM_CREATE"
    CLAIM_MODIFY = "CLAIM_MODIFY"
    CLAIM_CANCEL = "CLAIM_CANCEL"
    CLAIM_STATUS_CHANGE = "CLAIM_STATUS_CHANGE"
    ACCIDENT_CREATE = "ACCIDENT_CREATE"
    ACCIDENT_MODIFY = "ACCIDENT_MODIFY"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    DOCUMENT_VIEW = "DOCUMENT_VIEW"
    DOCUMENT_DOWNLOAD = "DOCUMENT_DOWNLOAD"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    DOCUMENT_TYPE_MODIFY = "DOCUMENT_TYPE_MODIFY"
    DOCUMENT_SCAN_STARTED = "DOCUMENT_SCAN_STARTED"
    DOCUMENT_SCAN_COMPLETED = "DOCUMENT_SCAN_COMPLETED"
    DOCUMENT_SCAN_REJECTED = "DOCUMENT_SCAN_REJECTED"
    OCR_REQUEST = "OCR_REQUEST"
    OCR_COMPLETE = "OCR_COMPLETE"
    OCR_FAILED = "OCR_FAILED"
    AI_EXTRACTION_COMPLETE = "AI_EXTRACTION_COMPLETE"
    FACT_CONFIRM = "FACT_CONFIRM"
    FACT_MODIFY = "FACT_MODIFY"
    FACT_REJECT = "FACT_REJECT"
    POLICY_VERSION_RESOLVED = "POLICY_VERSION_RESOLVED"
    POLICY_VERSION_RESOLUTION_FAILED = "POLICY_VERSION_RESOLUTION_FAILED"
    ASSESSMENT_CREATED = "ASSESSMENT_CREATED"
    ASSESSMENT_COMPLETED = "ASSESSMENT_COMPLETED"
    CALCULATION_EXECUTE = "CALCULATION_EXECUTE"
    CALCULATION_COMPLETE = "CALCULATION_COMPLETE"
    CALCULATION_FAILED = "CALCULATION_FAILED"
    CALCULATION_RECALCULATE = "CALCULATION_RECALCULATE"
    CALCULATION_VERSION_CREATED = "CALCULATION_VERSION_CREATED"
    EVIDENCE_BUILD = "EVIDENCE_BUILD"
    EVIDENCE_VIEW = "EVIDENCE_VIEW"
    DECISION_TRACE_VIEW = "DECISION_TRACE_VIEW"
    POLICY_EVIDENCE_VIEW = "POLICY_EVIDENCE_VIEW"
    POLICY_VERIFICATION_REVIEW = "POLICY_VERIFICATION_REVIEW"
    POLICY_VERIFICATION_PROMOTE = "POLICY_VERIFICATION_PROMOTE"
    REVIEW_CREATE = "REVIEW_CREATE"
    REVIEW_ASSIGN = "REVIEW_ASSIGN"
    REVIEW_ACCEPT = "REVIEW_ACCEPT"
    REVIEW_APPROVE = "REVIEW_APPROVE"
    REVIEW_MODIFY = "REVIEW_MODIFY"
    REVIEW_DOCUMENT_REQUEST = "REVIEW_DOCUMENT_REQUEST"
    REVIEW_DOCUMENT_SUBMITTED = "REVIEW_DOCUMENT_SUBMITTED"
    REVIEW_RESUMED = "REVIEW_RESUMED"
    REVIEW_UNDETERMINED = "REVIEW_UNDETERMINED"
    REVIEW_COMPLETE = "REVIEW_COMPLETE"
    SESSION_REVOKE = "SESSION_REVOKE"


class AuditResult(enum.StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


class AuditLog(Base):
    __tablename__ = "audit_logs"

    audit_id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.user_id"), index=True)
    event_type: Mapped[AuditEventType] = mapped_column(Enum(AuditEventType), index=True)
    object_type: Mapped[str | None] = mapped_column(String(100))
    object_id: Mapped[str | None] = mapped_column(String(100))
    claim_id: Mapped[uuid.UUID | None] = mapped_column(index=True)
    request_id: Mapped[str] = mapped_column(String(100), index=True)
    source_ip: Mapped[str | None] = mapped_column(String(45))
    before_value: Mapped[dict[str, Any] | None] = mapped_column(JSON)
    after_value: Mapped[dict[str, Any] | None] = mapped_column(JSON)
    result: Mapped[AuditResult] = mapped_column(Enum(AuditResult))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now)
